/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AccountRestrictedRouteImport } from './routes/account-restricted'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyEmailPendingRouteImport } from './routes/verify-email-pending'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated.appointments'
import { Route as AuthenticatedAvailabilitiesRouteImport } from './routes/_authenticated.availabilities'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated.doctors'
import { Route as AuthenticatedHealthRecordsRouteImport } from './routes/_authenticated.health-records'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated.reviews'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedFindDoctorIndexRouteImport } from './routes/_authenticated.find-doctor.index'
import { Route as AuthenticatedFindDoctorDoctorIdRouteImport } from './routes/_authenticated.find-doctor.$doctorId'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated.patients.$patientId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRestrictedRoute = AccountRestrictedRouteImport.update({
  id: '/account-restricted',
  path: '/account-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailPendingRoute = VerifyEmailPendingRouteImport.update({
  id: '/verify-email-pending',
  path: '/verify-email-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvailabilitiesRoute =
  AuthenticatedAvailabilitiesRouteImport.update({
    id: '/availabilities',
    path: '/availabilities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRecordsRoute =
  AuthenticatedHealthRecordsRouteImport.update({
    id: '/health-records',
    path: '/health-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFindDoctorIndexRoute =
  AuthenticatedFindDoctorIndexRouteImport.update({
    id: '/find-doctor/',
    path: '/find-doctor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFindDoctorDoctorIdRoute =
  AuthenticatedFindDoctorDoctorIdRouteImport.update({
    id: '/find-doctor/$doctorId',
    path: '/find-doctor/$doctorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/account-restricted': typeof AccountRestrictedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/availabilities': typeof AuthenticatedAvailabilitiesRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/health-records': typeof AuthenticatedHealthRecordsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/find-doctor/$doctorId': typeof AuthenticatedFindDoctorDoctorIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/find-doctor/': typeof AuthenticatedFindDoctorIndexRoute
}
export interface FileRoutesByTo {
  '/account-restricted': typeof AccountRestrictedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/availabilities': typeof AuthenticatedAvailabilitiesRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/health-records': typeof AuthenticatedHealthRecordsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/find-doctor/$doctorId': typeof AuthenticatedFindDoctorDoctorIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/find-doctor': typeof AuthenticatedFindDoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/account-restricted': typeof AccountRestrictedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/availabilities': typeof AuthenticatedAvailabilitiesRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
  '/_authenticated/health-records': typeof AuthenticatedHealthRecordsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/find-doctor/$doctorId': typeof AuthenticatedFindDoctorDoctorIdRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/find-doctor/': typeof AuthenticatedFindDoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-restricted'
    | '/login'
    | '/register'
    | '/verify-email-pending'
    | '/appointments'
    | '/availabilities'
    | '/billing'
    | '/doctors'
    | '/health-records'
    | '/history'
    | '/reviews'
    | '/settings'
    | '/find-doctor/$doctorId'
    | '/patients/$patientId'
    | '/find-doctor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account-restricted'
    | '/login'
    | '/register'
    | '/verify-email-pending'
    | '/appointments'
    | '/availabilities'
    | '/billing'
    | '/doctors'
    | '/health-records'
    | '/history'
    | '/reviews'
    | '/settings'
    | '/'
    | '/find-doctor/$doctorId'
    | '/patients/$patientId'
    | '/find-doctor'
  id:
    | '__root__'
    | '/_authenticated'
    | '/account-restricted'
    | '/login'
    | '/register'
    | '/verify-email-pending'
    | '/_authenticated/appointments'
    | '/_authenticated/availabilities'
    | '/_authenticated/billing'
    | '/_authenticated/doctors'
    | '/_authenticated/health-records'
    | '/_authenticated/history'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/find-doctor/$doctorId'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/find-doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountRestrictedRoute: typeof AccountRestrictedRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailPendingRoute: typeof VerifyEmailPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-restricted': {
      id: '/account-restricted'
      path: '/account-restricted'
      fullPath: '/account-restricted'
      preLoaderRoute: typeof AccountRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email-pending': {
      id: '/verify-email-pending'
      path: '/verify-email-pending'
      fullPath: '/verify-email-pending'
      preLoaderRoute: typeof VerifyEmailPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/availabilities': {
      id: '/_authenticated/availabilities'
      path: '/availabilities'
      fullPath: '/availabilities'
      preLoaderRoute: typeof AuthenticatedAvailabilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health-records': {
      id: '/_authenticated/health-records'
      path: '/health-records'
      fullPath: '/health-records'
      preLoaderRoute: typeof AuthenticatedHealthRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/find-doctor/': {
      id: '/_authenticated/find-doctor/'
      path: '/find-doctor'
      fullPath: '/find-doctor/'
      preLoaderRoute: typeof AuthenticatedFindDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/find-doctor/$doctorId': {
      id: '/_authenticated/find-doctor/$doctorId'
      path: '/find-doctor/$doctorId'
      fullPath: '/find-doctor/$doctorId'
      preLoaderRoute: typeof AuthenticatedFindDoctorDoctorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAvailabilitiesRoute: typeof AuthenticatedAvailabilitiesRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
  AuthenticatedHealthRecordsRoute: typeof AuthenticatedHealthRecordsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFindDoctorDoctorIdRoute: typeof AuthenticatedFindDoctorDoctorIdRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedFindDoctorIndexRoute: typeof AuthenticatedFindDoctorIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAvailabilitiesRoute: AuthenticatedAvailabilitiesRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
  AuthenticatedHealthRecordsRoute: AuthenticatedHealthRecordsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFindDoctorDoctorIdRoute: AuthenticatedFindDoctorDoctorIdRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedFindDoctorIndexRoute: AuthenticatedFindDoctorIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountRestrictedRoute: AccountRestrictedRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailPendingRoute: VerifyEmailPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
